Repository jtr13/cc21fall1, pull requests merged in 2021-11, with the labels that each got.

#4 Add r_regress_classify.Rmd
  _bookdown.yml
  r_regress_classify.Rmd
Labels: cheatsheet

#14 Add section for Data Science Product Cycles in Enterprises talk
  _bookdown.yml
  ds_product_cycles_in_enterprises.Rmd
Labels: Workshops

#28 adding tibble_vs_data_frame.Rmd
  _bookdown.yml
  tibble_vs_data_frame.Rmd
Labels: tutorial

#22 Neo4j init submission
  _bookdown.yml
  neo4j_to_r.Rmd
  resources/neo4j_to_r/connection.png
  resources/neo4j_to_r/introduction.png
Labels: Data Visualization

#24 Icons and symbols in r
  _bookdown.yml
  icons_and_symbols_in_r.Rmd
Labels: Data Visualization

#29 Introduction to Time Series
  _bookdown.yml
  introduction_to_time_series.Rmd
Labels: tutorial

#34 My community contribution - an introduction to the lattice package
  _bookdown.yml
  intro_lattice_tutorial.Rmd
Labels: Data Visualization

#27 graph_animation
  _bookdown.yml
  graph_animation.Rmd
  resources/graph_animation/final.gif
Labels: Data Visualization

#20 Vhh2105 cc edav
  _bookdown.yml
  vipul_cc_edav_kickstart_r.Rmd
Labels: tutorial

#41 CC project for Jiang Zhu and Xuechun Bai
  _bookdown.yml
  caret_machine_learning_tutorial.Rmd
Labels: tutorial

#63 Update caret_machine_learning_tutorial.Rmd
  caret_machine_learning_tutorial.Rmd
Labels: tutorial

#7 Create interactive_graphs_tutorial.Rmd
  _bookdown.yml
  interactive_graphs_tutorial.Rmd
Labels: tutorial

#48 web scraping
  _bookdown.yml
  resources/web_scraping_rcurl_xml/CCP1.png
  resources/web_scraping_rcurl_xml/CCP2.png
  resources/web_scraping_rcurl_xml/CCP3.png
  resources/web_scraping_rcurl_xml/CCP4.png
  resources/web_scraping_rcurl_xml/CCP5.png
  resources/web_scraping_rcurl_xml/CCP6.png
  web_scraping_rcurl_xml_project.Rmd
Labels: tutorial

#25 Submission for my community contribution v Felix Yeung (fy2264)
  twitter_api_scrape_tutorial.Rmd
Labels: tutorial

#60 Use of ggprism and ggsci packages to change style and color
  _bookdown.yml
  ggprism_and_ggsci_cheatsheets.Rmd
Labels: cheatsheet

#62 Add quick_guide_to_eda.Rmd to the root directory
  _bookdown.yml
  quick_guide_to_eda.Rmd
Labels: tutorial

#61 Community Contribution Group 6
  _bookdown.yml
  linear_association.Rmd
  resources/Linear_Association/Linear_Association_console_output.jpg
  resources/Linear_Association/Linear_Association_error1.jpg
  resources/Linear_Association/Linear_Association_error2.jpg
  resources/Linear_Association/Linear_Association_example.jpg
Labels: demonstration

#13 adding my file
  _bookdown.yml
  make_lm_assumptions_plots.Rmd
Labels: Data Visualization

#57 Add files via upload
  _bookdown.yml
  nlp_eda_python.Rmd
Labels: tutorial

#16 supervised_learning_tutorial.Rmd
  _bookdown.yml
  supervised_learning_tutorial.Rmd
Labels: tutorial

#36 Add rmd_syntax_cheatsheet.Rmd
  _bookdown.yml
  rmd_syntax_cheatsheet.Rmd
Labels: cheatsheet

#18 added par_coord_plot cheatsheet
  _bookdown.yml
  parallel_coordinate_plots_cheatsheet.Rmd
Labels: cheatsheet

#39 Xuchen Wang Customized Sort
  _bookdown.yml
  r_customized_sort.Rmd
Labels: demonstration

#67 Add files via upload
  _bookdown.yml
  r_datasci_workflow_cheatsheet.Rmd
Labels: cheatsheet

#21 First revision of parallel coordinate plots in ggplot2
  _bookdown.yml
  parallel_coordinate_plots_ggplot2.Rmd
Labels: tutorial

#72 a linear regression bestiary/cheatseet to go deeper on econometrics
  _bookdown.yml
  linear_regression_bestiary.Rmd
  resources/linear_regression_bestiary/linear_regression_bestiary.pdf
Labels: cheatsheet

#52 submit community contribution, upload to github
  _bookdown.yml
  using_ggplot_in_python.Rmd
Labels: tutorial

#51 Icons and symbols in r
  _bookdown.yml
  icons_and_symbols_in_r.Rmd
  resources/icons_and_symbols_in_r/wmpeople1.TTF
Labels: tutorial

#37 Submission of github CC: Neo4j-GraphQL-cheatsheet.
  _bookdown.yml
  graphql_cheatsheet.Rmd
Labels: cheatsheet

#64 R for data challenges
  _bookdown.yml
  r_for_data_challenges.Rmd
  resources/r_for_data_challenges/train.csv
Labels: tutorial

#17 Create 30_questions_answers_for_r_interview.Rmd
  30_questions_answers_for_r_interview.Rmd
  _bookdown.yml
Labels: tutorial

#19 git_bash.Rmd
  _bookdown.yml
  git_bash.Rmd
Labels: tutorial

#73 initial commit
  _bookdown.yml
  stacked_bar_plot_for_relative_proportions_in_python.Rmd
Labels: Data Visualization

#30 Initial commit for CC.
  _bookdown.yml
  ggplot_graph.Rmd
Labels: tutorial

#75 Create web_scraping.Rmd
  _bookdown.yml
  web_scraping.Rmd
Labels: tutorial

#69 3d_visualization
  3d_visualization .Rmd
  _bookdown.yml
Labels: tutorial

#55 Submission for Community Contribution
  _bookdown.yml
  umap_viz.Rmd
Labels: tutorial

#38 ML_packages_R uploaded
  _bookdown.yml
  ml_packages_in_R.rmd
Labels: demonstration

#50 Introduction to Longitudinal Data and MLGM package_ Haoyang Shen
  .DS_Store
  _bookdown.yml
  introduction_to_longitudinal_data_and_mlgm.Rmd
  resources/.DS_Store
  resources/introduction_to_longitudinal_data_and_mlgm/.DS_Store
  resources/introduction_to_longitudinal_data_and_mlgm/multivariate.png
  resources/introduction_to_longitudinal_data_and_mlgm/univariate.png
Labels: Data Visualization

#70 Parallel coordinate plots
  _bookdown.yml
  parallel_coordinate_plots.Rmd
Labels: demonstration

#42 an3077 map reduce concept & comparision with R
  _bookdown.yml
  mapreduce_concept_and_comparision_with_r.Rmd
Labels: Workshops

#23 added my cc functional programming
  function_programming_purrr.Rmd
Labels: tutorial

#71 add tutorial
  _bookdown.yml
  add_tutorial.Rmd
Labels: tutorial

#90 Crime analysis
  crime_around_cu.Rmd
Labels: demonstration

#66 Analyse awss3 r
  Analyse_data_from_aws_s3_buckets_in_R2.Rmd
Labels: tutorial

#47 introduction to flexdashboard and shiny
  _bookdown.yml
  introduction_to_flexdashboard_shiny.Rmd
  resources/intro_to_flexdashboard_shiny/Categorical_Input.png
  resources/intro_to_flexdashboard_shiny/Ex1CodeGraph.png
  resources/intro_to_flexdashboard_shiny/Ex1CodeInput.png
  resources/intro_to_flexdashboard_shiny/Ex1Graph1.png
  resources/intro_to_flexdashboard_shiny/Ex1Graph2.png
  resources/intro_to_flexdashboard_shiny/Ex1Input.png
  resources/intro_to_flexdashboard_shiny/Ex2CodeGraph.png
  resources/intro_to_flexdashboard_shiny/Ex2CodeInput.png
  resources/intro_to_flexdashboard_shiny/Ex2Graph1.png
  resources/intro_to_flexdashboard_shiny/Ex2Graph2.png
  resources/intro_to_flexdashboard_shiny/Ex2Input1.png
  resources/intro_to_flexdashboard_shiny/Ex2Input2.png
  resources/intro_to_flexdashboard_shiny/Ex3CodeGraph.png
  resources/intro_to_flexdashboard_shiny/Ex3CodeInput.png
  resources/intro_to_flexdashboard_shiny/Ex3Graph.png
  resources/intro_to_flexdashboard_shiny/Ex3Input.jpg
  resources/intro_to_flexdashboard_shiny/Ex3InputSelected.jpg
  resources/intro_to_flexdashboard_shiny/Numerical_Input.png
  resources/intro_to_flexdashboard_shiny/arrange1.png
  resources/intro_to_flexdashboard_shiny/arrange2.png
  resources/intro_to_flexdashboard_shiny/arrange_out1.png
  resources/intro_to_flexdashboard_shiny/arrange_out2.png
  resources/intro_to_flexdashboard_shiny/bar.png
  resources/intro_to_flexdashboard_shiny/checkbox.png
  resources/intro_to_flexdashboard_shiny/constants.R
  resources/intro_to_flexdashboard_shiny/dataframe1.png
  resources/intro_to_flexdashboard_shiny/dataframe2.png
  resources/intro_to_flexdashboard_shiny/library.png
  resources/intro_to_flexdashboard_shiny/table.png
Labels: tutorial
